export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_CAMPGROUNDS = "LOAD_CAMPGROUNDS";
export const REMOVE_CAMPGROUNDS = "REMOVE_CAMPGROUNDS";