export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_CAMPGROUNDS = "LOAD_CAMPGROUNDS";
export const LOAD_CAMPGROUND_DETAIL = "LOAD_CAMPGROUND_DETAIL";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const REMOVE_CAMPGROUND = "REMOVE_CAMPGROUND";
export const REMOVE_COMMENT = "REMOVE_COMMENT";